openapi: 3.0.3
info:
  title: PP Member API
  version: 0.2.0
  description: Internal service providing member flight bookings to the BFF.
servers:
  - url: https://member.pp.internal
security:
  - bearerAuth: []
paths:
  /flightBookings:
    get:
      summary: Get pending flight bookings for the authenticated member
      operationId: getFlightBookings
      parameters:
        - in: query
          name: status
          description: Filter by flight booking status
          schema:
            type: string
            enum: [PENDING, CHECKED_IN, CANCELLED]
        - in: query
          name: from
          description: Earliest departure time (ISO8601)
          schema: { type: string, format: date-time }
        - in: query
          name: to
          description: Latest departure time (ISO8601)
          schema: { type: string, format: date-time }
        - in: query
          name: page
          schema: { type: integer, minimum: 1, default: 1 }
        - in: query
          name: pageSize
          schema: { type: integer, minimum: 1, maximum: 100, default: 50 }
      responses:
        "200":
          description: A page of member flight bookings
          content:
            application/json:
              schema:
                type: object
                required: [items, page, pageSize, total]
                properties:
                  page: { type: integer }
                  pageSize: { type: integer }
                  total: { type: integer }
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Flight"
        "401": { $ref: "#/components/responses/Unauthorized" }
        "5XX": { $ref: "#/components/responses/ServerError" }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    Unauthorized:
      description: Missing or invalid credentials
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Error" }
    ServerError:
      description: Server-side error
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Error" }
  schemas:
    Flight:
      type: object
      required:
        [id, number, departureAirport, departureTimeScheduled, departureTimeEstimated, terminal, status]
      properties:
        id: { type: string }
        number: { type: string }
        departureAirport: { type: string }
        departureTimeScheduled: { type: string, format: date-time }
        departureTimeEstimated: { type: string, format: date-time, nullable: true }
        terminal: { type: string, nullable: true }
        gate: { type: string, nullable: true }
        status: { type: string, enum: [ON_TIME, DELAYED, CANCELLED] }
    Error:
      type: object
      required: [code, message]
      properties:
        code: { type: string }
        message: { type: string }
        details: { type: object, additionalProperties: true, nullable: true }
